language: php

sudo: false

matrix:
  include:
    - php: hhvm-3.18
      dist: trusty
    - php: 5.3
      dist: precise
    - php: 5.4
      dist: trusty
    - php: 5.5
      dist: trusty
    - php: 5.6
      dist: xenial

before_script: travis_retry composer install

script: vendor/bin/phpunit
