language: php

sudo: false

matrix:
  include:
    - php: hhvm-3.18
      dist: trusty
    - php: 5.3
      dist: precise
    - php: 5.4
      dist: trusty
    - php: 5.5
      dist: trusty
    - php: 5.6
      dist: xenial
    - php: 7.0
      dist: xenial
    - php: 7.1
      dist: bionic
    - php: 7.2
      dist: bionic
    - php: 7.3
      dist: bionic

before_script: travis_retry composer install

script: vendor/bin/phpunit
