language: php
php:
  - 5.3
  - 5.4

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --dev

script:
  - phpunit

notifications:
  email:
    - lstrojny@php.net
