language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --dev

script:
  - phpunit --configuration phpunit.xml --colors --coverage-text

matrix:
  allow_failures:
    - php: hhvm
